### PR TITLE
Add Apitally to third party packages section in docs

### PR DESCRIPTION
**Pull request by itssimon**
# Summary

- Add an item for [Apitally](https://apitally.io) to the [third party packages page](https://www.starlette.io/third-party-packages/) in the docs.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
I think the third party packages is enough... No need for the middleware...

**Comment by itssimon** [comment]
Fair call. Done.

**Comment by Kludex** [comment]
Is this going to be the first commercial product included in this section?

Does it sound fair to you to promote your product without you even sponsoring the organization?

**Comment by itssimon** [comment]
I genuinely believe that this will add value to the community, despite being a commercial product.

There are a few other commercial products linked in the [Third party middleware](https://www.starlette.io/middleware/#third-party-middleware) section of the docs (e.g. Bugsnag, Rollbar).

Given Apitally is built with FastAPI, and hence Starlette, I do think sponsorship would be fair regardless of this mention in the docs. I will definitely consider it once Apitally is profitable!

**Review by Kludex — APPROVED** [review]

**Pull request merged**
