### PR TITLE
Add baize.asgi.FileResponse to docs

### PR DESCRIPTION
**Pull request by abersheeran**
About https://github.com/encode/starlette/issues/950#issuecomment-1141698946

### CODE REVIEW

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
Thank you 👍

**Review by adriangb — APPROVED** [review]

**Comment by rigilfanov** [comment]
The last two links lead to the Chinese version of the documentation.

Maybe need replace `zh-CN` to `en-US` in url addresses.

**Comment by Kludex** [comment]
PR welcome. 🙏

**Comment by abersheeran** [comment]
This is my negligence. Thank you for your correction.

**Pull request merged**
