### PR TITLE
Ensure pyyaml is installed before actually using it

### PR DESCRIPTION
**Pull request by Colin-b**
To avoid non user-friendly error message (NoneType does not have attribute whatever)

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Would it be reasonable to move the assertion check into `SchemaGenerator.__init__` instead?

I personally don't think that we need unit tests for "does this assertion fire" - the cost of adding that extra code in the codebase doesn't seem to justify being overly protective.

**Comment by Colin-b** [comment]
I don't use SchemaGenerator but if you are ok with the creation of the dunder init method within BaseSchemaGenerator I am willing to do it.

Do you want me to remove the test case as well then ?

**Comment by lovelydinosaur** [comment]
> but if you are ok with the creation of the dunder init method within BaseSchemaGenerator I am willing to do it.

Okay probably best not then. Might be some folks using `BaseSchemaGenerator`, but using a different (overridden) behavior for the docstrings.

In that case I'd suggest leaving the check where it currently is, but dropping the test case.

**Comment by Colin-b** [comment]
> In that case I'd suggest leaving the check where it currently is, but dropping the test case.

Done

**Comment by lovelydinosaur** [comment]
Great, thanks!

**Pull request merged**
