### PR TITLE
Allow render to access status code

### PR DESCRIPTION
**Pull request by walt-w**
Minor change the sequence for init status and body, so render can access status code

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Could you include an example of how you're using this?

I'm not convinced sure if moving the `self.body = ...` would be an improvement. It feels a bit like relying too much on internal implementation details. Also if we did move it, then we might instead want to move it further down, to just before the `.init_headers` call.

**Comment by walt-w** [comment]
Sorry for slow response. For example, I want the render to response like `{"status": 404, "message": "not found"} `automatically for kinds of status code, for now I can only pass the whole response dict manually. 
For move it before the `.init_headers`, it's a good idea. 
So all the question is, should render be able to access `Response` properties ?

**Comment by walt-w** [comment]
I've updated to move the render just before `.init_headers`

**Review by lovelydinosaur — APPROVED** [review]
Sure, I'm okay with this.

**Pull request merged**
