### PR TITLE
Downgrade mkdocs-material

### PR DESCRIPTION
**Pull request by Kludex**
- Solves https://github.com/encode/starlette/discussions/2437

### CODE REVIEW

**Comment by Kludex** [comment]
@encode/maintainers I need this to be approved. The docs are not working.

**Review by frankie567 — APPROVED** [review]
🚒👍

**Comment by MtkN1** [comment]
@Kludex Thank you for the fix! By the way, the same issue is occurring in encode/uvicorn docs as well.
https://www.uvicorn.org/

**Comment by Kludex** [comment]
Oh my god! 😢

**Comment by lovelydinosaur** [comment]
> the same issue is occurring in encode/uvicorn docs as well.

Hmmm... what's that about?

**Comment by Kludex** [comment]
> > the same issue is occurring in encode/uvicorn docs as well.
> 
> Hmmm... what's that about?

We need to downgrade the mkdocs-material there as well, and publish the docs. I didn't have time yet.

**Pull request merged**
