### PR TITLE
Add security flags to session cookie

### PR DESCRIPTION
**Pull request by HarrySky**
Flags: Secure, HttpOnly and SameSite=lax

SameSite flag can be set to 2 values:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies

I am making it "lax" by default, but maybe it should be configurable somehow?

### CODE REVIEW

**Comment by HarrySky** [comment]
Oh, I forgot that Secure header can only be used with HTTPS connections, that may be the reason why check failed

**Comment by HarrySky** [comment]
Should I add something like `secure: bool = False` to `__init__` and then add Secure flag if it is `True`?

**Comment by HarrySky** [comment]
@tomchristie can I add `# pragma: no cover` to line 30? I think we can't test that. Or should I change my code somehow?

**Comment by lovelydinosaur** [comment]
You can test with: TestClient(base_url=“https://testserver”)

**Comment by HarrySky** [comment]
@tomchristie added the test, local `./scripts/test` don't fail, but Travis check failed, what should I do? I did not find any CONTRIBUTING.md or something.

**Comment by HarrySky** [comment]
Just run `./scripts/lint` and it changed a lot of files by just removing lines between import, should I commit it?

Example from `git diff`:
```
 import pytest
-
 from starlette import status
 from starlette.testclient import TestClient
 from starlette.websockets import WebSocket, WebSocketDisconnect
```

**Comment by HarrySky** [comment]
Now I get this problem
`ERROR: /home/travis/build/encode/starlette/starlette/middleware/sessions.py Imports are incorrectly sorted.`

But nothing changed, only one space in imports was removed.

UPDATE: Fixed it :)

**Comment by HarrySky** [comment]
@tomchristie should I add or change something else in this pull request?

**Comment by lovelydinosaur** [comment]
Lovely stuff, yup! Should be a new release out sometime this week.

**Pull request merged**
