### PR TITLE
Fix regression on route paths with colons

### LINKED ISSUE #4892: When a url contains colon, it makes 404 response. After I upgrade fastapi from 0.75.0 to 0.77.1.
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
main.py

....
@app.post("/files:upload_homework")
async def create_file():
    ......

--------------------    
$ curl -X POST "http://127.0.0.1:8000/files:upload_homework"
{"detail":"Not Found"}%

------------
I run my fastapi App below command:

uvicorn main:app --host 0.0.0.0 --port 80
```

### Description

It works in below packages:

```
$ pip freeze
anyio==3.5.0
asgiref==3.5.0
click==8.0.4
fastapi==0.75.0
h11==0.13.0
httptools==0.4.0
idna==3.3
Jinja2==3.0.3
MarkupSafe==2.1.1
pydantic==1.9.0
python-dotenv==0.19.2
python-multipart==0.0.5
pytz==2022.1
PyYAML==6.0
six==1.16.0
sniffio==1.2.0
starlette==0.17.1
typing-extensions==4.1.1
uvicorn==0.17.6
uvloop==0.16.0
watchgod==0.8.1
websockets==10.2
```

It can not works below packages:
```
$ pip freeze                                                
anyio==3.5.0
asgiref==3.5.0
click==8.0.4
fastapi==0.77.1
h11==0.13.0
httptools==0.4.0
idna==3.3
Jinja2==3.0.3
MarkupSafe==2.1.1
pydantic==1.9.0
python-dotenv==0.19.2
python-multipart==0.0.5
pytz==2022.1
PyYAML==6.0
six==1.16.0
sniffio==1.2.0
starlette==0.19.1
typing-extensions==4.1.1
uvicorn==0.17.6
uvloop==0.16.0
watchgod==0.8.1
websockets==10.2

```

### Operating System

Linux, macOS

### Operating System Details

_No response_

### FastAPI Version

0.77.1

### Python Version

Python 3.9.12

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by florimondmanca**
Fixes https://github.com/tiangolo/fastapi/issues/4892 which was introduced in 0.18.0 via #1322.

Narrower alternative to #1657, that also reorganizes tests introduced by #1322 so that the "'Host' header matching should ignore ports" behavior is clearer.

(Matching when host string and requested `Host` have the exact same `:port` is the intuitive case. What's special is Starlette matches even in case of absent or different port in `Host`.)

### CODE REVIEW

**Review by Kludex — APPROVED** [review]
Thanks for this. 👍

**Comment by Kludex** [comment]
We can add a co-author when squashing for the original author. That's what I usually do, but act as you like. 🙏

**Comment by florimondmanca** [comment]
I can add @bodograumann as a co-author then. :)

**Comment by bodograumann** [comment]
Thanks for merging this fix. I'm really happy this project is so active!

**Comment by Kludex** [comment]
Thank you for bringing a solution right away! 🎉

This will be available on Starlette 0.20.2, which is going to be released today. JFYK :)

**Pull request merged**
