### PR TITLE
Update staticfiles.py

### PR DESCRIPTION
**Pull request by dmontagu**
Add the f for the f strings.

Noticed while investigating #534

### CODE REVIEW

**Comment by dmontagu** [comment]
Issue #534 also pointed out the issue of calling the static folder "statics" vs. "static" when using the `packages` option. Is there a reason for this? (I would understand if at this point the goal was just to prevent breaking changes.)

**Comment by dmontagu** [comment]
Segmentation fault for python 3.8-dev? That's weird.

**Comment by dmontagu** [comment]
@tomchristie perhaps related to https://github.com/python-pillow/Pillow/issues/3884 ? They suggest deleting the travis build caches.

**Comment by lovelydinosaur** [comment]
Cache deleted. Build restarted.

**Review by blueyed — APPROVED** [review]

**Comment by lovelydinosaur** [comment]
Thanks for the bump @blueyed! 3.8 build passed after I restarted it.

**Pull request merged**
