### PR TITLE
Use explicit origin when with credentials

### LINKED ISSUE #1832: CORSMiddleware does not provide explicit origin although Authorization header is present
### Discussed in https://github.com/encode/starlette/discussions/1823

<div type='discussions-op-text'>

<sup>Originally posted by **gyusang** August 26, 2022</sup>
When sending a CORS request with credentials, wildcard origin is rejected by the standard.
The CORS middleware handles this case when cookies are included, but is missing the case when `Authorization` header is present.
https://github.com/encode/starlette/blob/31164e346b9bd1ce17d968e1301c3bb2c23bb418/starlette/middleware/cors.py#L164-L165
Since Token authentication is also widely used these days, I believe explicit header should be returned when `Authorization` header is present.</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/1832">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/1832/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by gyusang**
- [ ] Initially raised as discussion #1823 

Edit by @Kludex:
- Closes #1832

### CODE REVIEW

**Comment by Kludex** [comment]
Can you add a test, please?

**Comment by gyusang** [comment]
> Can you add a test, please?

Yes, I have added a test for the added functionality.

**Comment by Kludex** [comment]
I'm not sure about this idea. I don't see any CORS implementation using a custom logic for cookies or authorization headers.

But I do see a different logic when "allow_credentials" is true, that we don't have.

**Comment by Kludex** [comment]
@gyusang I think we still need a bit of discussion around this. I took a bit of time to search around, and I didn't find any implementation that does what we do, nor expand the logic as this PR suggests.

Let's continue this on #1832, please. 🙏

**Pull request closed without merging**
