### PR TITLE
Session Backend

### PR DESCRIPTION
**Pull request by akhilputhiry**
All work is done by @alex-oleshkevich in https://github.com/encode/starlette/pull/499
I am just trying to get this merged, since I need this feature https://github.com/encode/starlette/issues/284

### CODE REVIEW

**Comment by blueyed** [comment]
@akhilputhiry 
Not much I can do - I have several PRs idling myself.. :/

**Comment by blueyed** [comment]
@akhilputhiry 
JFI: I am using https://github.com/blueyed/starlette/tree/next myself with those being merged there.

**Comment by theruziev** [comment]
@akhilputhiry What about expire session. If I authorise an user and it go away without logout, how remove session in redis or in other backends? May be we need add expiring method in abstract class and realize in specific backends

**Comment by akhilputhiry** [comment]
@theruziev There is already a `remove` method available. Those who want to auto expire can make use of this method. Probably they can run a background job which compares the current time vs time in session (timestamp can be stored as part of session)

**Comment by theruziev** [comment]
@akhilputhiry good point about background job. Or we can set TTL if backend supports it. Redis and Memcached support TTL

**Comment by gnat** [comment]
Just wanted to say very nice PR. Useful for clusters of machines sharing user sessions. I feel like many of us have implemented this independently for our projects.

**Comment by Kludex** [comment]
As you said, duplicated of #499 , so closing this. I'll see if we can take a decision on that PR soon.

Sorry for taking so long.

EDIT: The duplication is on #284.

**Pull request closed without merging**
