### PR TITLE
ci: Travis: re-add py38

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/encode/starlette/pull/547

Not sure what the problem is/was, but it works for me in https://github.com/blueyed/starlette/pull/7 (https://travis-ci.com/blueyed/starlette/jobs/215744722).

### CODE REVIEW

**Comment by blueyed** [comment]
py38 works, but there are (new) mypy failures:
```
+mypy starlette --ignore-missing-imports --disallow-untyped-defs
starlette/testclient.py:158: error: No binding for nonlocal 'request_complete' found
starlette/testclient.py:158: error: No binding for nonlocal 'response_complete' found
starlette/testclient.py:186: error: No binding for nonlocal 'raw_kwargs' found
starlette/testclient.py:186: error: No binding for nonlocal 'response_started' found
starlette/testclient.py:186: error: No binding for nonlocal 'response_complete' found
starlette/testclient.py:186: error: No binding for nonlocal 'template' found
starlette/testclient.py:186: error: No binding for nonlocal 'context' found
The command "scripts/test" exited with 1.
```

**Comment by blueyed** [comment]
See https://github.com/encode/starlette/pull/576 for the mypy fix.

**Comment by lovelydinosaur** [comment]
Great, try bringing it up to date with master and we’ll see where we’re at.

**Comment by blueyed** [comment]
@tomchristie 
Worked as expected.

**Comment by lovelydinosaur** [comment]
Ace. Thanks.

**Pull request merged**
