### PR TITLE
Version 0.14.0

### PR DESCRIPTION
**Pull request by erewok**
### Added

* Starlette now officially supports Python3.9.
* In `StreamingResponse`, allow custom async iterator such as objects from classes implementing `__aiter__`.
* Allow usage of `functools.partial` async handlers in Python versions 3.6 and 3.7.
* Add 418 I'm A Teapot status code.

### Changed

* Create tasks from handler coroutines before sending them to `asyncio.wait`.
* Use `format_exception` instead of `format_tb` in `ServerErrorMiddleware`'s `debug` responses.
* Be more lenient with handler arguments when using the `requires` decorator.

### CODE REVIEW

**Comment by euri10** [comment]
not a semver pro but shouldn't that be a 0.14.0 ?

**Comment by JayH5** [comment]
I _thiiink_ this just scrapes under the requirements for a version 0.14.0. There shouldn't be any breaking changes and the additions are all slight relaxations of existing interfaces.

Maybe worth adding a point that this release "officially supports Python 3.9"?

**Comment by florimondmanca** [comment]
Thanks!

Agreed, given the changelog entries this sounds like an obvious candidate for 0.14.0. :-)

**Comment by JayH5** [comment]
But..version numbers are free. So happy to do v0.14.0

**Comment by erewok** [comment]
Sounds fine to me: switch to `0.14.0.` (but I reused the same git branch...)

**Review by florimondmanca — APPROVED** [review]

**Review by JayH5 — APPROVED** [review]

**Pull request merged**
