### PR TITLE
Fixed - async __call__ not run/awaited in the BackgroundTask

### PR DESCRIPTION
**Pull request by dpr-0**
Reference to #886

### CODE REVIEW

**Review by Kludex — COMMENTED** [review]
On `starlette/endpoints.py` we also use the same `asyncio.iscoroutinefunction`. We probably want to use the same `iscoroutinefunction` there as well.

Maybe we should move the function to other module?

**Comment by dpr-0** [comment]
Yeah, so should I work on this branch or checkout to a new branch for this `iscoroutinefunction` function?

**Comment by Kludex** [comment]
It can be here.

**Comment by dpr-0** [comment]
> It can be here.

I see. Thanks for reviewing this pull request. Considering current module names might be not completely suitable for this function, it seems like there can be a new module like `utils.py` for this function.

**Comment by Kludex** [comment]
I guess the function was moved, so we could also do the replacement on the `starlette/endpoints.py`?

**Comment by dpr-0** [comment]
> I guess the function was moved, so we could also do the replacement on the `starlette/endpoints.py`?

Hi, I am back for this thread. Should I do the replacement now?

**Comment by Kludex** [comment]
I'm not sure. I think we should look for #1444, but I don't know the opinion of the other members.

**Comment by dpr-0** [comment]
> I'm not sure. I think we should look for #1444, but I don't know the opinion of the other members.

Yeah, I understand that, please let me know if there is any update about this thread. Thanks.
Maybe there is other tickets I can be assigned right now.

**Comment by Kludex** [comment]
@dpr-0 Thanks for this PR! Also, sorry for taking long to take action here.

I'm going to push forward to #1444, so I'll be closing this.

**Comment by dpr-0** [comment]
@Kludex No problem, Thanks for fixing this issue at #1444 !

**Comment by Kludex** [comment]
Thank you for the patience here! 🙇‍♂️

**Pull request closed without merging**
