### PR TITLE
Stop `body_stream` in case `more_body=False`

### LINKED ISSUE #2093: `HTTPMiddleware` breaks `BackgroundTasks` in the same connection
- [x] Initially raised as a discussion in [the FastAPI repo](https://github.com/tiangolo/fastapi/discussions/7168#discussioncomment-5387343).

Consider the following simple example of background tasks through Starlette:
`server.py`
```py
import logging
from time import sleep

from starlette.applications import Starlette
from starlette.background import BackgroundTasks
from starlette.middleware import Middleware
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.routing import Route

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)


class CustomMiddleware(BaseHTTPMiddleware):
    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        return await call_next(request)


def create_task(request: Request) -> JSONResponse:
    logging.info("Entered POST method")
    tasks = BackgroundTasks()
    tasks.add_task(background_task)
    message = {"status": "Task created"}
    return JSONResponse(message, background=tasks, status_code=201)


def background_task() -> None:
    logging.info("Started background task")
    sleep(10)
    logging.info("Finished background task")


routes = [Route("/task", endpoint=create_task, methods=["POST"])]
middleware = [Middleware(CustomMiddleware)]
app = Starlette(routes=routes, middleware=middleware)
```

I start this code with `uvicorn server:app --reload`.

Then I start the task twice in one connection using this code:
`client.py`
```py
from httpx import Client

with Client(base_url="http://localhost:8000") as client:
    client.post("/task")
    client.post("/task")
```

Which results in a sequential execution of background tasks (and read timeout from the client as a consequence):
```
[2023-03-23 19:32:08] [INFO] Entered POST method
INFO:     127.0.0.1:51448 - "POST /task HTTP/1.1" 201 Created
[2023-03-23 19:32:08] [INFO] Started background task
[2023-03-23 19:32:18] [INFO] Finished background task
[2023-03-23 19:32:18] [INFO] Entered POST method
[2023-03-23 19:32:18] [INFO] Started background task
[2023-03-23 19:32:29] [INFO] Finished background task
```

If I just send simple curl requests (`curl -X 'POST' 'http://127.0.0.1:8000/task'`) one after the other (so they are different connections), everything works as expected:
```
[2023-03-23 19:44:35] [INFO] Entered POST method
INFO:     127.0.0.1:55528 - "POST /task HTTP/1.1" 201 Created
[2023-03-23 19:44:35] [INFO] Started background task
[2023-03-23 19:44:37] [INFO] Entered POST method
INFO:     127.0.0.1:55532 - "POST /task HTTP/1.1" 201 Created
[2023-03-23 19:44:37] [INFO] Started background task
[2023-03-23 19:44:45] [INFO] Finished background task
[2023-03-23 19:44:47] [INFO] Finished background task
```

It looks like this regression was introduced in Starlette [0.23.1](https://github.com/encode/starlette/releases/tag/0.23.1), [this PR](https://github.com/encode/starlette/pull/1940). If I pin Starlette to 0.23.0 everything works fine.

### PR DESCRIPTION
**Pull request by Kludex**
Closes https://github.com/encode/starlette/issues/2093

We need to check how this interacts with FastAPI: https://github.com/encode/starlette/pull/1609#issuecomment-1307600095

I've tested this with the following application:

```py
from asyncio import sleep
from typing import Any, Coroutine

from starlette.applications import Starlette
from starlette.background import BackgroundTasks
from starlette.middleware import Middleware
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.middleware.gzip import GZipMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse, Response, StreamingResponse
from starlette.routing import Route

n = 0


async def task() -> None:
    global n
    local = n
    print(f"Start {local}.")
    n += 1
    await sleep(3)
    print(f"Finish {local}.")


class CustomMiddleware(BaseHTTPMiddleware):
    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Coroutine[Any, Any, Response]:
        return await call_next(request)


async def homepage(request: Request) -> ...:
    tasks = BackgroundTasks()
    tasks.add_task(task)
    return JSONResponse(content={"potato": "potato"}, background=tasks)


def exc_stream(request: Request):
    return StreamingResponse(_generate_faulty_stream())


def _generate_faulty_stream():
    yield b"Ok"
    raise Exception("Faulty Stream")


def empty(request: Request):
    return Response(status_code=200)


app = Starlette(
    routes=[
        Route("/", endpoint=homepage),
        Route("/stream", endpoint=exc_stream),
        Route("/empty", endpoint=empty),
    ],
    middleware=[Middleware(GZipMiddleware), Middleware(CustomMiddleware), Middleware(GZipMiddleware)],
)
```

Run with `uvicorn --http h11 main:app --reload`.

I've used the following client:

```py
from httpx import Client

with Client(base_url="http://localhost:8000") as client:
    print("Calling '/'")
    for n in range(5):
        client.get("/")

    print("Calling '/empty'")
    for n in range(5):
        client.get("/empty")

#     print("Calling '/stream'")
#     for n in range(5):
#         client.get("/stream")
```

Run with `python client.py`.

### CODE REVIEW

**Comment by Kludex** [comment]
I've tested against FastAPI main branch, and it looks like it doesn't break the dependency injection system, as the previous attempt.

@encode/maintainers Can someone review it, please? I want us to make sure that we don't break FastAPI. If you have a suggestion about how to test this, it would be appreciated as well.

**Comment by alex-oleshkevich** [comment]
That's ok. `break` closes the iterator just like if there are no more data.

**Comment by adriangb** [comment]
On `fastapi==0.100.0` https://github.com/encode/starlette/pull/1609#issuecomment-1306767290 works correctly for me either with the version of starlette it ships with (`0.27.X`) nor `0.28.0`. It also seems to work with this branch. I once again confirmed it's broken on `fastapi==0.85.0`. So it seems that at the very least this change does not break FastAPI in the same way as the previous one did.

As long as we can confirm via a test that this fixes the issues with background tasks this looks good to me 👍🏻

**Review by adriangb — APPROVED** [review]

**Comment by Kludex** [comment]
I gave another round of manual test with FastAPI, and it works as expected - not breaking their dependency system. 🙏

**Comment by b4stien** [comment]
Hi, this PR [regressed this issue](https://github.com/tiangolo/fastapi/discussions/8577#discussioncomment-8914357), I've tested manually that commenting those two lines allowed `app_exc` not to be None and to be subsequently raised.

_(I'm no expert in ASGI and starlette codebase, don't understand the root issue that this change was trying to fix and I'm then unable to propose a better fix...)_

**Pull request merged**
