### PR TITLE
Add listener for disconnect to FileResponse

### LINKED ISSUE #1301: FileResponse Stream continues streaming after http.disconnect
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

While downloading a file provided via `FileResponse` the starlette application continues "sending" chunks even if the client aborts.
This is the same bug as I found reported and fixed for StreamResponse. References:
 - issue in Fastapi repo: https://github.com/tiangolo/fastapi/issues/1342
 - fixing PR in starlett repo: https://github.com/encode/starlette/pull/839

### To reproduce

```python
async def stream_file_response(request: Request) -> FileResponse:
    bg = BackgroundTask(...)
    return FileResponse(
        path=PATH, filename="example.png", background=bg
    )

###############################################################3

response = requests.get(
    f"http://{HOST}:{PORT}/file",
    stream=True,
)
response.close()
```

For details see following PR.

### Expected behavior

FileResponse is also listening for http.disconnect and aborts stream if client disconnects.

### Actual behavior

The application doesn't start with the backgroundtask right away, but continues sending all the cunks first until finished.

### Debugging material

See `tests/test_response_abort.py` in following PR.

### Environment

- OS: Linux Arch
- Python version: Python 3.9.7
- Starlette version: master, 0.15.0

### Additional context

n.a.

### PR DESCRIPTION
**Pull request by idotobi**
This fixes #1301.

This makes `FileResponse` behave the same way as `StreamResponse`,
namely aborting sending data once a `http.disconnect` is received from the client.

Note that this behaviour is currently not tested in `StreamResponse`.
I found one way to test this behaviour. However, it would require to add `httpx` as a testing requirement hence it is not part of the PR yet.
`FileResponse` is even more tricky to test without having a way to mark a `FileResponse` as finished (would require a new property).

### CODE REVIEW

**Comment by idotobi** [comment]
Note: The code for `__call__` and `listen_for_disconnect` are implemented exactly as in `StreamResponse`. It might be worthwhile to make `FileResponse` inherit from `StreamResponse` in the future as they are quite similar in nature.

**Comment by Kludex** [comment]
Interesting. We don't have a specific test for `StramingResponse` as well, for the same case.

**Comment by Kludex** [comment]
> I found one way to test this behaviour. However, it would require to add httpx as a testing requirement hence it is not part of the PR yet.

@idotobi How?

**Comment by lovelydinosaur** [comment]
Hiya @idotobi - thank you for the neatly tackled bit of work here.

I'd like to close this off with the justification as outlined on https://github.com/encode/starlette/issues/1301

There's always a complexity trade-off in these kinds of cases, and my feeling is that Starlette ought to lean very strongly towards as-simple-as-possible-wherever-possible.

*(Something we need to get better at as a team is making sure we're fielding incoming requests like this, so that you're not sending time on neatly done pull requests like this one, and then having them closed off. We're working on that.)*

**Comment by idotobi** [comment]
@Kludex : It was a rather messy prototype, where I had to remove some asserts within the httpx testclient, so I wouldn't recommend it for production usage.

The idea was basically to exchange the `receive` callback in the app definition 

```py
    async def app(scope, receive, send):
        async def receive() -> dict:
            return {"type": "http.disconnect"}
```

This way the server would abort the connection itself, if it listened to `http.disconnect`.
...As I said. Not pretty but sadly there is to Testclient I found that was able to send disconnect while waiting on the response out-of-the-box.

**Comment by idotobi** [comment]
@tomchristie : No worries. I learned a bit on the way, so it's no time wasted.

**Pull request closed without merging**
