### PR TITLE
Plaintext response with status

### PR DESCRIPTION
**Pull request by berislavlopac**
As discussed in #138 I have replaced explicit integer status codes with the `status` consonants, and added the option for `PlainTextResponse` to automatically add content if just the status code is passed (specifically, if the content passed is an integer that exists in `http.HTTPStatus`.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
> and added the option for PlainTextResponse to automatically add content if just the status code is passed

I think we should possibly treat these two separately.
Definitely want `PlainTextResponse(status_code=404)` to set the content automatically.
Not sure if we want to replace integer status codes everywhere in the codebase.

**Comment by lovelydinosaur** [comment]
*Maybe* we'll take 'em both in one, just not sure yet.

**Comment by lovelydinosaur** [comment]
@berislavlopac We *could* subclass `__init__` (eg. see RedirectResponse) but 🤷‍♂️

**Comment by berislavlopac** [comment]
Of course; I was concerned about the `PlainTextResponse()` use case. But since `200` is the default for `status_code` anyway, I suppose it would just return `OK`. Good point.

**Comment by alexbotello** [comment]
What would you think about overriding the `render` method of `PlainTextResponse` instead of the `__init__`? This way class signatures can remain consistent as well as being cleaner I feel.

Maybe something like:
```python
def render(self, content: typing.Any) -> bytes:
    if isintance(content, http.HTTPStatus):
        self.status_code = content
        content = http.HTTPStatus(content).phrase
    elif isinstance(content, bytes):
        return content
    return content.encode(self.charset)
```
So that `PlainTextResponse(404) -> "Not Found"` 

Thoughts?

**Comment by berislavlopac** [comment]
@alexbotello Possibly, but I might have approached this the wrong way in the first place; please check my [latest comment](https://github.com/encode/starlette/issues/138#issuecomment-433870739) on the original issue.

**Comment by alexbotello** [comment]
@berislavlopac I think the approach is fine. `HTTPException` is for use with "app" in scope and with the ExceptionMiddlware. But Starlette is also modular so it makes sense that we should have this manual functionality as well in case when a user wants to use `PlainTextResponse` independently.  If a user is performing validation  or etc. and what’s to manually send back a status message, this is a good use case.

@tomchristie feel free to correct me if I am off base

**Comment by lovelydinosaur** [comment]
Starting to use `isort` has added a lot of simple conflicts here.
I think best to treat this as 2 PRs in any case - not fully decided on each part yet.

**Comment by berislavlopac** [comment]
@tomchristie No problem, I can separate them. What is your opinion on `__init__` vs `render`?

**Comment by lovelydinosaur** [comment]
@berislavlopac Not sure.

**Comment by lovelydinosaur** [comment]
Let's treat these two issues separately. Fairly sure we want the PlainTextResponse behavior. Less obvious if we want to use verbose status codes throughout.

**Pull request closed without merging**
