### PR TITLE
Draft for the async test client (#440)

### PR DESCRIPTION
**Pull request by gvbgduh**

### CODE REVIEW

**Comment by gvbgduh** [comment]
Based on `requests_async`. ASGI 2 is not supported for now. Works together with `@pytest.mark.asyncio` that runs the event loop.

**Comment by lovelydinosaur** [comment]
So, a suggestion:

I think for this incoming iteration we should maybe stop using `async with TestClient()` for the lifespan handling. There's no particular reason we need to be bundling Lifespan handling up in the same class as the HTTP client. Perhaps a standalone `async with AppLifespan(app):` would be better? (Perhaps also with an API for non-context-manager style usage)

**Comment by gvbgduh** [comment]
Yes, that sounds reasonable, it'll give much better granularity as having the lifespan task in the loop might not always be convenient. 
On the other hand, having the lifespan handled helps to take care of the app events (eg. `startup` or `shutdown`), so the app can be more closely replicated within the test case. I'm very happy to follow this.

Having said that, I still might need a bit of clarity as I have some architectural confusion.
It probably should be an additional test client (like AsyncTestClient or anything else?). Mostly for backwards compatibility with existing test cases. And if so `requests_async.ASGISession` takes care of everything for this already, but is there need for an alias within the `starlette`?
Or, more generally, should `requests_async` be brought into dependencies?

This might also impact `AppLifespan` implementation as it seems it can inherit and extend `requests_async.ASGISession` quite well, so the same module [`requests_async.asgi`] might be a good place. But I might be missing bits of the whole picture. 

Therefore, some advice would be much appreciated and I can target my PR more precisely.

**Comment by jordic** [comment]
Hey just to share with yours, we just developed this small asgi test client, 
https://github.com/vinissimus/async-asgi-testclient
(Only for understanding better the main spec, but we are using it)

**Comment by lovelydinosaur** [comment]
Right now let's punt on this.
Yes we *will* want to point at `requests_async` or something as an async test client, but I'm also confident that pulling the lifespan stuff out of the rest of the test client is *also* going to be the right thing for us to do, so let's keep those bits seperate.

**Pull request closed without merging**
