### PR TITLE
apply pyupgrade --py36-plus

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
I'd like to add a `.pre-commit-config.yaml` to enforce this too

**Comment by graingert** [comment]
@JayH5 can I get a review on this please?

**Review by lovelydinosaur — APPROVED** [review]
Yup, all good. 👍

**Comment by graingert** [comment]
@tomchristie I don't have permissions to merge this

**Comment by graingert** [comment]
@tomchristie do you want me to configure pre-commit?

**Comment by lovelydinosaur** [comment]
pre-commit what?

**Comment by graingert** [comment]
@asottile 's pre-commit https://github.com/asottile/pyupgrade#as-a-pre-commit-hook

**Comment by lovelydinosaur** [comment]
No, thanks.

**Pull request merged**
