### PR TITLE
[WIP] Handle scope["root_path"] and scope["path"] as per ASGI spec 

### PR DESCRIPTION
**Pull request by frankie567**
- [X] Initially raised as issue #1336 

## Rationale

This is an exploratory work as how to solve issue #1336. The issue details the problem quite well but in a nutshell:

* The issue arises when using a `Mount` router alongside the `root_path` option.
* We consider that `path` is the remainder of the whole path striped from `root_path`. As pointed out [here](https://github.com/django/asgiref/issues/229#issuecomment-765583185), this is not how the ASGI spec was imagined: `path` *should* contain `root_path`.
* As a consequence, every route matching is done assuming the `root_path* is *not present* in the path.
* Besides, we use this behavior to  recursively handle `Mount` routers, by adding the router prefix on `root_path` and stripping `path` until we match the single route:

https://github.com/encode/starlette/blob/e3de71f1433568a3f7ac3dc69ef86cf4f72f5651/starlette/routing.py#L378-L390

Notice that we define an `app_root_path` to keep track of the original `root_path`.

The way I understand it, we should keep both `path` and `root_path` *untouched*. It's a shame of course because we won't be able to handle `Mount` elegantly as we do now.

## Current work status

First of all, I added a unit test to reproduce the issue.

Then, I've tried a first approach to solve it which consists of two things:

* Instead of using `path` and `root_path` directly, use internal variables `current_path` and `current_root_path` (admittedly, this is a very uninspired naming) to allow our recursive approach
* Take care of stripping the `root_path` from the `path` so we can match properly, both in `Route` and `Mount`

This solves the specific problem but breaks other parts of the code. Obviously, every parts of the routing which makes use of the `path` will need to account for this `root_path`, e.g. in `WebSocketRoute` or in `Router`, in [the part where we make slash redirects](https://github.com/encode/starlette/blob/e3de71f1433568a3f7ac3dc69ef86cf4f72f5651/starlette/routing.py#L694-L707).

An idea I had to tackle this would be to have a common `prepare_scope` which could be called by the Route classes to prepare the path, add the "internal" variables, while keeping the original `path` and `root_path` untouched.
 
Before going further, I would be interested in your views and opinions about this so we can take the right path.

Cheers!

### CODE REVIEW

**Comment by Kludex** [comment]
@frankie567 Do you mind if I keep this open?

**Comment by frankie567** [comment]
Oh yes, sure, @Kludex! I closed it in order to not keep too much stale things, but definitely willing to work on this when needed 🙂

**Comment by Kludex** [comment]
Sorry for the long waiting time.

I find this too complex, and I need time to sit, and get more knowledge around it.

**Comment by frankie567** [comment]
No worries 🙂 Feel free to ping me when needed!

**Comment by Kludex** [comment]
@frankie567 I know that I said that I'd like to keep this around, but I'm going to close it for now (hope it's fine).

In any case, I'm sorry for the long time to do something here.

**Comment by frankie567** [comment]
No problem, @Kludex 😄 Keep up the great work!

**Pull request closed without merging**
