### PR TITLE
Added official Python 3.12 support

### PR DESCRIPTION
**Pull request by agronholm**
# Summary

- Adds Python 3.12 to CI
- Updates `pytest` to a compatible version
- Adds the `Python :: 3.12` classifier

# Checklist

- [X] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [X] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [X] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by agronholm** [comment]
I looked for documentation to update but couldn't find anything relevant.

**Review by Kludex — APPROVED** [review]
Thanks 🙏

**Comment by Kludex** [comment]
Don't we need to point at 3.12-dev?

**Comment by agronholm** [comment]
> Don't we need to point at 3.12-dev?

Nope, the `allow-prereleases: true` flag takes care of that.

**Comment by Kludex** [comment]
Thanks 🙏

**Pull request merged**
