### PR TITLE
Support either `cleanup` or `shutdown` in ASGI lifespan messages

### LINKED ISSUE #130: Support `shutdown` as a synonym for `cleanup`
* Support either `cleanup` or `shutdown` as the ASGI lifespan message name.
* Update uvicorn to move to shutdown - https://github.com/encode/uvicorn/issues/233
* Finally, after a small period of time, drop `cleanup`

Easy PR for a contributor to jump on would be addressing the first part of this, and supporting either name.

### PR DESCRIPTION
**Pull request by alexbotello**
Closes #130

### CODE REVIEW

**Review by lovelydinosaur — CHANGES_REQUESTED** [review]
Looking good! One very minor tweak to make.

**Comment by alexbotello** [comment]
Not sure how to resolve the tests for this one. Or if we would even want to, since the current tests will be perfectly fine once we drop support of 'cleanup'

**Comment by lovelydinosaur** [comment]
Using `# pragma: no cover` to exclude specific lines in contexts like this is perfectly okay. Let’s do that.

**Comment by lovelydinosaur** [comment]
Looks great! Will merge this once in at a keyboard and able to push a new release. Thanks!!

**Review by lovelydinosaur — APPROVED** [review]

**Comment by lovelydinosaur** [comment]
Nice one!

**Comment by lovelydinosaur** [comment]
Released as 0.5.5

**Pull request merged**
