### PR TITLE
Change github issues template

### LINKED ISSUE #1370: Use new GitHub issue template
Use same template as `uvicorn` on issues:

- https://github.com/encode/uvicorn/issues/new?assignees=&labels=&template=feature-request.yml
- https://github.com/encode/uvicorn/blob/master/.github/ISSUE_TEMPLATE/feature-request.yml

It avoids people creating issues like this i.e. ignoring completely the template.

### PR DESCRIPTION
**Pull request by aminalaee**
Closes #1370 and updates Github issues templates.

### CODE REVIEW

**Comment by aminalaee** [comment]
Strange as the `bug-report.yml` shows an error: `Name must be unique`.

**Comment by Kludex** [comment]
Yeah... I had the same on uvicorn. What I did was merge into master on my fork and see if the template was alright :thinking:

**Comment by aminalaee** [comment]
Thanks, I just checked and it looks good.
I've tried to keep it as close as possible to uvicorn.

https://github.com/aminalaee/starlette/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml
https://github.com/aminalaee/starlette/blob/master/.github/ISSUE_TEMPLATE/feature-request.yml

**Review by Kludex — APPROVED** [review]
Thanks! :tada:

**Pull request merged**
