### PR TITLE
♻️ Use asgiref typing instead of starlette types

### PR DESCRIPTION
**Pull request by Kludex**
Since `uvicorn` added `asgiref` as a dependency (for typing), we probably want to do the same here.

I didn't discuss this yet, so I'm not sure about the opinion of other members, feel free to comment if you see this. I'm going to write more about this later on.

### CODE REVIEW

**Comment by JayH5** [comment]
Not against this eventually as it'd be nice to have shared types between encode projects. However, a first step might be to just re-export the `asgiref` types as the ones we use under `starlette.types`. That would greatly reduce the changes and make it a lot easier for our users to upgrade.

**Comment by Kludex** [comment]
> However, a first step might be to just re-export the asgiref types as the ones we use under starlette.types.

I thought about that, but I think the `Message` will be an issue, as there's no compatibility with `asgiref`. `Message` would be something like `Union[ASGIReceiveEvent, ASGISendEvent]`, but this will probably cause a lot of `mypy` conflicts.

That being said, I'm going to try your suggestion in a few days. 👍

**Comment by Kludex** [comment]
Ok. I tried that.

```python
import typing

from asgiref.typing import Scope  # noqa: F401
from asgiref.typing import (
    ASGI3Application,
    ASGIReceiveCallable,
    ASGIReceiveEvent,
    ASGISendCallable,
    ASGISendEvent,
)

Message = typing.Union[ASGIReceiveEvent, ASGISendEvent]

Receive = ASGIReceiveCallable
Send = ASGISendCallable

ASGIApp = ASGI3Application
```
And I got:
```bash
Found 518 errors in 19 files (checked 62 source files)
```
:laughing: :rofl:

**Comment by Kludex** [comment]
I'll close this because I'll not have time to solve the conflicts here. There are ~280. 

If we don't do this, when using `uvicorn.run`, we'll always have to ignore the `mypy` error now that `uvicorn` is almost fully `mypy` compliant.

**Pull request closed without merging**
