### PR TITLE
Add starlette-cramjam link in docs

### PR DESCRIPTION
**Pull request by vincentsarago**
This PR adds a mention to starlette-cramjam: a compression middleware adding brotli, gzip and deflate algorithm.

### CODE REVIEW

**Comment by Kludex** [comment]
@JayH5 @tomchristie Any thoughts about how we should handle PRs like this? Is there any parameter to decide if they should be included or not?

**Comment by lovelydinosaur** [comment]
@Kludex Happy to link to any third packages, yup!

(Tho looks like the test suite is failing for unrelated reasons)

**Comment by Kludex** [comment]
Test suit is failing due to Python 3.9.7 upgrade. Development branch should also fail if I trigger it. 

Thanks! :tada:

**Review by Kludex — APPROVED** [review]
Thanks @vincentsarago ! :tada:

**Comment by vincentsarago** [comment]
Thanks @Kludex 🙏

**Pull request merged**
