### PR TITLE
Raise `WebSocketDisconnect` when `WebSocket.send()` excepts `IOError`

### PR DESCRIPTION
**Pull request by Kludex**
- I don't think I can test this can be tested without fixing https://github.com/encode/starlette/issues/947.

I think we should fix the above issue before merging this.

Uvicorn PR: https://github.com/encode/uvicorn/pull/2218

### CODE REVIEW

**Comment by Kludex** [comment]
- I've created https://github.com/encode/starlette/pull/2427. 🙏

**Comment by Kludex** [comment]
It turns out that now it's impossible to create a test with the `TestClient` with the changes I've implemented on #2427. 😆

It's because the `TestClient` will exit on client disconnect. I think the behavior is fine tho.

**Comment by Kludex** [comment]
@encode/maintainers someone? 🙏

**Review by michaeloliverx — APPROVED** [review]
Don't have a lot of context here but it looks fine at first glance and there is a test.

**Pull request merged**
