### PR TITLE
Fix #472 (AssertionError with middleware and TemplateResponse)

### LINKED ISSUE #472: AssertionError with middleware and TemplateResponse
```diff
diff --git i/tests/test_templates.py w/tests/test_templates.py
index b48373e..57dee91 100644
--- i/tests/test_templates.py
+++ w/tests/test_templates.py
@@ -20,6 +20,11 @@ def test_templates(tmpdir):
     async def homepage(request):
         return templates.TemplateResponse("index.html", {"request": request})

+    @app.middleware("http")
+    async def noop(request, call_next):
+        response = await call_next(request)
+        return response
+
     client = TestClient(app)
     response = client.get("/")
     assert response.text == "<html>Hello, <a href='http://testserver/'>world</a></html>"
```

causes:
```
tests/test_templates.py:29: in test_templates
    response = client.get("/")
.venv/lib/python3.7/site-packages/requests/sessions.py:546: in get
    return self.request('GET', url, **kwargs)
starlette/testclient.py:421: in request
    json=json,
.venv/lib/python3.7/site-packages/requests/sessions.py:533: in request
    resp = self.send(prep, **send_kwargs)
.venv/lib/python3.7/site-packages/requests/sessions.py:646: in send
    r = adapter.send(request, **kwargs)
starlette/testclient.py:238: in send
    raise exc from None
starlette/testclient.py:235: in send
    loop.run_until_complete(self.app(scope, receive, send))
/usr/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
starlette/applications.py:134: in __call__
    await self.error_middleware(scope, receive, send)
starlette/middleware/errors.py:122: in __call__
    raise exc from None
starlette/middleware/errors.py:100: in __call__
    await self.app(scope, receive, _send)
starlette/middleware/base.py:25: in __call__
    response = await self.dispatch_func(request, self.call_next)
tests/test_templates.py:21: in noop
    response = await call_next(request)
starlette/middleware/base.py:47: in call_next
    assert message["type"] == "http.response.start"
E   AssertionError
```
`message` is `{'type': 'http.response.template', 'template': <Template 'index.html'>, 'context': {'request': <starlette.requests.Request object at 0x7ff4a2d21e48>}}` there.

This appears to be an issue with the test client only though.
Do I understand it correctly that the "http.response.template" extension is only used with tests?

### PR DESCRIPTION
**Pull request by moriyoshi**
This patch fixes #472.

### CODE REVIEW

**Comment by moriyoshi** [comment]
The failing mypy checks are addressed in the following PRs:

https://github.com/encode/starlette/pull/1072
https://github.com/python/typeshed/pull/4650

**Comment by moriyoshi** [comment]
Now that both PRs have been merged, anyone can have a look at this?

> #1072
> python/typeshed#4650

**Comment by moriyoshi** [comment]
Anyone?

**Comment by GabrieleCalarota** [comment]
What's missing to this to be merged?
Is there a workaround in the meantime?

**Comment by aminalaee** [comment]
@moriyoshi Can you update please?

**Comment by Kludex** [comment]
I'm closing this as it's an old PR, and the author is no longer interested in this content.

Let's work on a fix/trial for #472 on another PR.

**Pull request closed without merging**
