### PR TITLE
Correct spelling of asynchronous in events.md

### PR DESCRIPTION
**Pull request by sondrelg**
🙂

### CODE REVIEW

**Review by aminalaee — APPROVED** [review]
Thank you for this.

**Comment by aminalaee** [comment]
Maybe you can update title/description to the exact fix?

**Comment by sondrelg** [comment]
Does this title seem ok @aminalaee? 🙂 Feel free to change the PR description if you have suggestions.

**Comment by Kludex** [comment]
Thanks @sondrelg ! :tada:

**Pull request merged**
