### PR TITLE
Feat/sse

### PR DESCRIPTION
**Pull request by sysid**
New Response Type: EventSourceResponse
Implementation of ServerSentEvent (SSE) Protocol

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Heya! Impressive bit of work here.

I think what we'd really like would be to push for this to be a third-party package, so that it can be maintained independantly of Starlette itself.

We'd be able to link out to it from the main "responses" documentation, in the same way that we currently do for third-party middleware: https://www.starlette.io/middleware/#third-party-middleware

**Comment by sysid** [comment]
Thanks Tom for your quick response.
Followed your advice: [https://github.com/sysid/sse-starlette](https://github.com/sysid/sse-starlette).
Link from Starlette documentation would be nice.

**Comment by sysid** [comment]
Thanks Tom for your quick response.
Followed your advice: [https://github.com/sysid/sse-starlette](https://github.com/sysid/sse-starlette).
Link from Starlette documentation would be nice.

 

mail: thomas.we.weber@gmx.de

 
 

Gesendet: Mittwoch, 19. Februar 2020 um 12:44 Uhr
Von: "Tom Christie" <notifications@github.com>
An: encode/starlette <starlette@noreply.github.com>
Cc: sysid <thomas.we.weber@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [encode/starlette] Feat/sse (#757)


Heya! Impressive bit of work here.

I think what we'd really like would be to push for this to be a third-party package, so that it can be maintained independantly of Starlette itself.

We'd be able to link out to it from the main "responses" documentation, in the same way that we currently do for third-party middleware: https://www.starlette.io/middleware/#third-party-middleware

**Comment by lovelydinosaur** [comment]
@sysid - Great! Submit a pull request to the "responses" docs, adding a third party section in a similar style to the "middleware" docs, and add a link the the package there. Nice work!

**Pull request closed without merging**
