### PR TITLE
Allow returning memoryview in StreamingResponse

### PR DESCRIPTION
**Pull request by bschoenmaeckers**
# Summary

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Review by adriangb — APPROVED** [review]
Makes sense to me!

**Comment by Kludex** [comment]
What's the use case? To create the `memoryview` you need `bytes` or `bytearray` anyway...

**Comment by bschoenmaeckers** [comment]
Memoryview allows you to efficiently return a slice of the original bytes value without copying. This is especially convenient when you want to strip some prefix or header of some value in memory you don’t control.

**Comment by adriangb** [comment]
Yup I'd say the use cases are varied, it allows moving around bytes with zero copying.

**Comment by Kludex** [comment]
This is a PR without description, and there's a single discussion that mentioned this feature request (that is 4 years old) without reactions.

Also, this can be easily done by overriding the `stream_response` method. And that's what we've always recommended.

**Comment by adriangb** [comment]
Feel free to revert it if you don’t agree. To me it made sense and was simple.

**Comment by danielballan** [comment]
Thanks for this! Useful when transmitting buffers from numpy array without copying.

**Pull request merged**
