### PR TITLE
Bump anyio requirement from 3.x to 3.x, 4.x

### PR DESCRIPTION
**Pull request by Kludex**
Checking if `anyio` 4.0 dev branch works with Starlette.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Given that this passes, should we switch it up?
Would `"anyio>=3,<=4"` do what we'd want here? (Any 3.x, 4.x version)

**Comment by Kludex** [comment]
No, that will not get `4.x`. `anyio>=3.4,<5.0` should do the job.

**Comment by lovelydinosaur** [comment]
Ah yeah. Shall we switch over to that in this pull request then?

**Comment by Kludex** [comment]
I was waiting the anyio release, but yeah...

**Review by lovelydinosaur — APPROVED** [review]

**Pull request merged**
