### PR TITLE
Try to make Request generic over State

### PR DESCRIPTION
**Pull request by adriangb**
https://github.com/encode/starlette/pull/2065#issuecomment-1643474342

TODO: how do we let users at runtime customize the state creation function? Currently, Starlette creates the Request object so it can't be as simple as a constructor parameter. For FastAPI I suppose it could introspect the type hints to get the generic argument.

### CODE REVIEW

**Comment by adriangb** [comment]
@Kludex any idea how to get this to work nicely with mypy?

**Comment by Kludex** [comment]
> @Kludex any idea how to get this to work nicely with mypy?

I think I have some comments around about it. I'll look later, and share it here. (It maybe in our WhatsApp conversation... I'll check.)

**Comment by Kludex** [comment]
I've created https://github.com/python/typing/discussions/1457.

**Comment by michaeloliverx** [comment]
On an semi related side note I hacked around this in FastAPI by doing this:
```python
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from typing import Annotated, TypedDict, cast

from fastapi import Depends, FastAPI, Request


class State(TypedDict):
    foo: str
    bar: str


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[State, None]:
    ...


async def get_state(request: Request) -> State:
    return cast(State, request.state._state)


StateDependency = Annotated[State, Depends(get_state)]

```

**Comment by Kludex** [comment]
I'll close this, since the Python type system still doesn't support this.

- We can watch https://github.com/python/typing/discussions/1457 and related discussions.

**Pull request closed without merging**
