### PR TITLE
use explicit Optional[...] for parameters with None as a default in datastructures.py

### PR DESCRIPTION
**Pull request by adriangb**
See https://www.python.org/dev/peps/pep-0484/#union-types

### CODE REVIEW

**Comment by Kludex** [comment]
> See [https://www.python.org/dev/peps/pep-0484/\#id29](https://www.python.org/dev/peps/pep-0484/%5C#id29)

The link is "not found".

**Comment by adriangb** [comment]
Weird, it got mangled, it should be https://www.python.org/dev/peps/pep-0484/#union-types

**Comment by adriangb** [comment]
Specifically:

> A past version of this PEP allowed type checkers to assume an optional type when the default value is None, as in this code:

```python
def handle_employee(e: Employee = None): ...
```

> This would have been treated as equivalent to:

```python
def handle_employee(e: Optional[Employee] = None) -> None: ...
```

> This is no longer the recommended behavior. Type checkers should move towards requiring the optional type to be made explicit.

**Review by lovelydinosaur — APPROVED** [review]
Sure. Don't know what the motivation is behind...

> This is no longer the recommended behavior. Type checkers should move towards requiring the optional type to be made explicit.

But happy enough either ways. 😌

**Review by Kludex — APPROVED** [review]

**Comment by adriangb** [comment]
There's probably discussions on the topic in BPO and such. Personally my motivation is just to make sure the project works as well as possible with type checkers.

**Pull request merged**
