### PR TITLE
Fix: Resolve the issue where the directory itself being a symlink does not work.

### LINKED ISSUE #2646: When the directory itself being a symlink does not work.
My test code:

```python
from fastapi import FastAPI
import uvicorn

from staticfiles import StaticFiles

app = FastAPI()
app.mount("/music", StaticFiles(directory="/home/hanxi/work/xiaomusic/music", follow_symlink=True), name="music")

uvicorn.run(
    app,
    host=["::", "0.0.0.0"],
    port=3333,
)
```

The directory /home/hanxi/work/xiaomusic/music is a symlink.

```
> ls -l /home/hanxi/work/xiaomusic/music
lrwxrwxrwx 1 hanxi hanxi 26 Apr 30 12:10 /home/hanxi/work/xiaomusic/music -> /home/hanxi/nas/data/music
```

I fix this in https://github.com/hanxi/starlette/commit/831cb5d255832d9f704ffd7be49b4184cd301dd6

Need pr?

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2646">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2646/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by hanxi**
# Summary

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

Fixed #2646 

I test https://github.com/encode/starlette/security/advisories/GHSA-v5gw-mw7f-84px case. test result is 404 Not Found.

### CODE REVIEW

**Comment by Kludex** [comment]
A test case is needed here.

**Comment by hanxi** [comment]
Okay, I'll add the test cases.

**Comment by hanxi** [comment]
done.

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
Thanks!

**Pull request merged**
