### PR TITLE
Customizable request class

### PR DESCRIPTION
**Pull request by alex-oleshkevich**
This allows users to change the default `Request` class.

There are following customization options:
1. Set `request_class` on Route constructor:
```python
Route('/', endpoint, request_class=MyRequest)
```
This has higher precedence than `request_class` defined in HTTPEndpoint class.

2. Set `request_class` in HTTPEndpoint:
```python
class MyEndpoint(HTTPEndpoint):
    request_class = MyRequest

    def get(self, request: MyRequest): ...
```

### CODE REVIEW

**Comment by florimondmanca** [comment]
Dropping by out of curiosity — could you explicit some practical use cases that would motivate the ability to swap the request class? Maybe this is linked to an existing issue?

**Comment by em92** [comment]
> could you explicit some practical use cases that would motivate the ability to swap the request class?

I would store this to `MyRequest` constructor. https://github.com/em92/quakelive-local-ratings/blob/879c354c4f8d25965c93f6a1c84e68c48f1aabb4/qllr/endpoints.py#L53-L68

**Comment by alex-oleshkevich** [comment]
I am building an application that has a custom Request class. This class has extra methods related to it (input validation, helpers to get values from GET/POST,  user IP, and many other helpers). 

In order to make use of it, I have to completely extend Route/HTTPEndpoint/request_response names. It is a huge overhead here.

Also, it is useful for frameworks built on top of Starlette. They often have own request classes (look at HttpRequest in Django and Request in DRF).

**Comment by erewok** [comment]
I like this idea. I am in favor of figuring out how to add it. It would also close this issue I opened awhile ago related to having custom JSON decoders: https://github.com/encode/starlette/issues/715.

**Comment by Kludex** [comment]
@alex-oleshkevich After this whole time, do you still want this feature? Is it something you'd want to discuss?

**Comment by alex-oleshkevich** [comment]
Yes, i use custom request time each time. My class has some extra properties and utilities.

**Comment by alex-oleshkevich** [comment]
There can be a workaround with a simple decorator that inspects view signature and injects a needed request instance.

**Pull request closed without merging**
