### PR TITLE
show how to import BaseHTTPMiddleware

### PR DESCRIPTION
**Pull request by lsmith77**
just saves people some time searching for how to get BaseHTTPMiddleware imported

### CODE REVIEW

**Comment by Kludex** [comment]
Thanks @lsmith77 ! :tada:

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
I'm not allowed to edit this PR. Could you rebase it @lsmith77 ?

**Comment by lsmith77** [comment]
done and green!

**Comment by Kludex** [comment]
Thanks again! @lsmith77

**Pull request merged**
