### PR TITLE
Support generator function to manage startup/shutdown.

### PR DESCRIPTION
**Pull request by lovelydinosaur**
An alternate implementation of #785

- [x] Refactor lifespan to run as an async generator
- [x] Allow `lifespan_context=...` argument to `Starlette` and `Router`.
- [x] Add `app` argument to the lifespan context function.

End result API would be allowing the application to take a single `async` generator function, that can encapsulate any required startup/shutdown logic.

Taking the example in #785, you'd end up with this kind of pattern...

```python
async def lifespan(app):
    async with db.ConnectionPool() as app.state.pool:
        yield

app = Starlette(routes=..., middleware=..., lifespan=lifespan)
```

### CODE REVIEW

**Comment by sm-Fifteen** [comment]
Using this approach, I have two questions:
1. Couldn't an application use a sync generator instead of an async one as their lifespan context? After all, [servers are forbidden from accepting connections until the a startup complete event is recieved](https://asgi.readthedocs.io/en/latest/specs/lifespan.html#startup-complete), so there isn't a whole lot of things that could preempt the startup coroutines regardless of whether the functions being called are blocknig or not. There might not be any async code to run on startup or shutdown.
2. Could this be a step in fixing #649?

**Comment by lovelydinosaur** [comment]
1. The async function is sufficient, since it can run either sync or async code. It *might* be graceful to be able to have it accept either kind of function, or it might be unnecessary extra noise?
2. Potentially, yeah.

**Comment by sm-Fifteen** [comment]
>     1. The async function is sufficient, since it can run either sync or async code. It _might_ be graceful to be able to have it accept either kind of function, or it might be unnecessary extra noise?

Having looked into it, you can't loop though a sync and an async iterator with the same kind of loop, so it would mean duplicating the iteration part, which would be unneccessarily noisy. It probably wouldn't be worth it anyway, so nervermind that.

>     2. Potentially, yeah.

That's good if it turns out that way, lifespan has a number of caveats that make it unreliable (#649) or impractical (what this PR attempts to fix) to use right now. That's probably out of scope for this PR, though.

**Comment by iksteen** [comment]
Works for me, just be sure to properly document that lifespan and startup/shutdown are mutually exclusive (at least, in this implementation).

**Comment by lovelydinosaur** [comment]
> Couldn't an application use a sync generator instead of an async one as their lifespan context?

Alrighty, for completeness I've added support for the function to be *either* a generator or an async generator.

**Comment by rugleb** [comment]
When can we expect a release with this feature?

**Pull request merged**
