### PR TITLE
(docs) Adding Sentry: Exceptions

### PR DESCRIPTION
**Pull request by smeubank**
[related discussion](https://github.com/encode/starlette/discussions/1787#discussioncomment-3314878)

Making this a separate PR to ensure discussion of how to appropriately add this to the page

related: https://github.com/encode/starlette/pull/2062

### CODE REVIEW

**Comment by Kludex** [comment]
This needs to be better structured to get in this section.

**Comment by smeubank** [comment]
> This needs to be better structured to get in this section.

👍  agreed. What type of structure would you suggest? I was thinking to add under "3rd party" similar to the middleware docs page. But that feels a little out of place when it is the only one.

Should I add some example code snippet? I also don't want to be overly verbose or for it to feel like a Sentry add in Starlette docs

**Comment by Kludex** [comment]
I guess something like:
1. Explaining why someone would use Sentry, focused on the error management.
2. A snippet on how to configure it with Starlette, a basic explanation on what happens, and a link to Sentry's documentation for more details.

This was @tomchristie 's idea, it may be better if he shares a bit his thoughts... :eyes:

**Comment by Kludex** [comment]
Closing it as stale. Please, let's discuss how this should look like on the discussion.

**Pull request closed without merging**
