### PR TITLE
Added Range support to Staticfiles

### PR DESCRIPTION
**Pull request by kevinastone**
Allows staticfiles to serve assets with range header support to serve
partial fragments.

This is necessary when serving media assets used in HLS or Dash
playlists that rely on Range header support to serve fragments from a
larger media container.

### CODE REVIEW

**Comment by kevinastone** [comment]
Let me know what you think and if this functionality should belong in Starlette.  This PR could use some additional cleanup and improvements to better match the spec for Range requests (including multipart ranges and suffix ranges).

**Comment by Kludex** [comment]
@abersheeran You've created something similar somewhere, right? Do you know where? 🥺

**Comment by abersheeran** [comment]
@Kludex Yes, it's at https://github.com/abersheeran/baize/blob/master/baize/asgi.py#L406

**Comment by Kludex** [comment]
Thank you! 👍

**Comment by Kludex** [comment]
Related to https://github.com/encode/starlette/issues/22

**Comment by lovelydinosaur** [comment]
Looking at this now, I think we should probably just say that the functionality `StaticFiles` currently provides is as much as we'd like it to do. There's still scope for someone to implement a more fully functional third-party package that adds extra options here.

**Pull request closed without merging**
