### PR TITLE
Do not send empty data to `StreamingResponse` on `BaseHTTPMiddleware`

### LINKED ISSUE #803: Gzip Middleware content-length is incorrect
The following exception is thrown when I use uvicorn to drive my starlette project. After control variates, I am sure this is caused by Gzip Middleware.

```
  File "C:\Users\AberS\Documents\Github\index.py\.venv\lib\site-packages\h11\_writers.py", line 102, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length") 
h11._util.LocalProtocolError: Too little data for declared Content-Length
```

### PR DESCRIPTION
**Pull request by Kludex**
- This seems more correct than #1608.
- Alternative to #1579
- ~Closes #803~ not really related.

### CODE REVIEW

**Comment by Kludex** [comment]
@hiranp @abersheeran Can you confirm that the issue is solved with this PR? 🙏

**Review by abersheeran — APPROVED** [review]

**Review by adriangb — APPROVED** [review]

**Comment by Kludex** [comment]
Thanks @abersheeran and @adriangb :)

**Comment by MrSalman333** [comment]
Hello, 

this PR breaks down stream FastApi >_< 

the tare down in the decencies in FastApi doesn't work as expected after it .

**Comment by adriangb** [comment]
Do you have a minimal reproducible example? Keep in mind that FastAPI uses a pinned Starlette version.

**Comment by MrSalman333** [comment]
yah , I'm typing a complete example now ,,,

FastAPI just updated Starlette version this is why we found the issue ,,

EDIT: 

```py
import logging

from fastapi import Depends, FastAPI
from fastapi.middleware.base import BaseHTTPMiddleware
from starlette.middleware import Middleware
from starlette.middleware.base import BaseHTTPMiddleware


class CustomMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        return await call_next(request)


app = FastAPI(middleware=[Middleware(CustomMiddleware)])


def dependency_a():
    yield "A"
    logging.warning("WILL NOT RUN")


def dependency_b():
    yield "B"
    logging.warning("WILL NOT RUN")


def dependency_c():
    yield "C"
    logging.warning("WILL RUN")


@app.get(
    "/issue",
    dependencies=[
        Depends(dependency_a),
    ],
)
def show_dependencies_issue(
    b=Depends(dependency_b),
    c=Depends(dependency_c),
):
    return {"status": "ok"}
```

ok so if I remove the CustomMiddleware from the app. all warning messages will log.
but with the code above ,, only the message with  "WILL RUN" will run ,, because it is the last decencies


this issue disappear if I revert this change. 
but I'm sure it will cause other issues,

**Comment by MrSalman333** [comment]
example added

**Comment by adriangb** [comment]
Try this:

```python
import logging

import anyio
import httpx
from fastapi import Depends, FastAPI, Response
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.middleware import Middleware


class CustomMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        return await call_next(request)


app = FastAPI(middleware=[Middleware(CustomMiddleware)])


def dependency_a(response: Response):
    try:
        yield "A"
    finally:
        logging.warning("A")


def dependency_b(response: Response):
    try:
        yield "B"
    finally:
        logging.warning("B")


def dependency_c(response: Response):
    try:
        yield "C"
    finally:
        logging.warning("C")


@app.get(
    "/issue",
    dependencies=[
        Depends(dependency_a),
    ],
)
def show_dependencies_issue(
    b=Depends(dependency_b),
    c=Depends(dependency_c),
):
    return {"status": "ok"}


async def main() -> None:
    async with httpx.AsyncClient(app=app, base_url="http://example.com") as client:
        await client.get("/issue")

anyio.run(main)
```

What version of FastAPI does your example work in?

**Comment by Kludex** [comment]
I can reproduce the issue.

I've isolated the commit, it's confirmed. This changes the behavior.

**Comment by MrSalman333** [comment]
lates version[0.86.0] "the current master"  

but the issue should show up on > 0.85, because they updated Starlette version to [0.20.4]

**Comment by Kludex** [comment]
Let's understand if this commit has an issue or if the problem is the FastAPI assumptions around dependencies.

I'll be available to check this tonight (Amsterdam time), jfyk.

**Comment by MrSalman333** [comment]
take a look at this file from FastAPI I think u can get there working assumptions

https://github.com/tiangolo/fastapi/blob/master/fastapi/applications.py

check their override of `build_middleware_stack ` and the comment in it

**Comment by MrSalman333** [comment]
I'll open a PR on FastAPI that fixes the issue from there side ,, but it will change the behavior of contextvars on FastAPI so not sure if it will get accepted,

just letting you know

**Comment by Kludex** [comment]
> Try this:
> 
> ```python
> import logging
> 
> import anyio
> import httpx
> from fastapi import Depends, FastAPI, Response
> from starlette.middleware.base import BaseHTTPMiddleware
> from starlette.middleware import Middleware
> 
> 
> class CustomMiddleware(BaseHTTPMiddleware):
>     async def dispatch(self, request, call_next):
>         return await call_next(request)
> 
> 
> app = FastAPI(middleware=[Middleware(CustomMiddleware)])
> 
> 
> def dependency_a(response: Response):
>     try:
>         yield "A"
>     finally:
>         logging.warning("A")
> 
> 
> def dependency_b(response: Response):
>     try:
>         yield "B"
>     finally:
>         logging.warning("B")
> 
> 
> def dependency_c(response: Response):
>     try:
>         yield "C"
>     finally:
>         logging.warning("C")
> 
> 
> @app.get(
>     "/issue",
>     dependencies=[
>         Depends(dependency_a),
>     ],
> )
> def show_dependencies_issue(
>     b=Depends(dependency_b),
>     c=Depends(dependency_c),
> ):
>     return {"status": "ok"}
> 
> 
> async def main() -> None:
>     async with httpx.AsyncClient(app=app, base_url="http://example.com") as client:
>         await client.get("/issue")
> 
> anyio.run(main)
> ```
> 
> What version of FastAPI does your example work in?

Hmmm... This example shows that the dependency is not _teardown-ed_. Using this code with `uvicorn`, you can see the logs on `SIGINT`.

**Comment by MrSalman333** [comment]
yah , sorry I didn't respond ,, I was confused of a bit because it worked. then I remembered I applied my stash.
unfortunately it didn't work

**Comment by adriangb** [comment]
> Hmmm... This example shows that the dependency is not teardown-ed. Using this code with uvicorn, you can see the logs on SIGINT.

When I run this on `fastapi==0.86.0` and `starlette==0.20.4` I see all 3 logs emitted. With the same versions the original example does indeed give me only `WARNING:root:WILL RUN`.

**Comment by Kludex** [comment]
> > Hmmm... This example shows that the dependency is not teardown-ed. Using this code with uvicorn, you can see the logs on SIGINT.
> 
> When I run this on `fastapi==0.86.0` and `starlette==0.20.4` I see all 3 logs emitted. With the same versions the original example does indeed give me only `WARNING:root:WILL RUN`.

I didn't check this scenario. I'll check later on.

**Comment by MrSalman333** [comment]
> > Hmmm... This example shows that the dependency is not teardown-ed. Using this code with uvicorn, you can see the logs on SIGINT.
> 
> When I run this on `fastapi==0.86.0` and `starlette==0.20.4` I see all 3 logs emitted. With the same versions the original example does indeed give me only `WARNING:root:WILL RUN`.

running this with `uvicorn`, still shows the issue 

in our project the test client will not show the same behavior, in the tests this works with no issue 

so using try ... finally with AsyncClient will not show this issue

**Comment by Kludex** [comment]
The problem is only with `def` dependencies.

~I think we know where the issue is... I'll check.~

**Comment by Kludex** [comment]
From `AsyncExitStackMiddleware`:

image

```python
Traceback (most recent call last):
  File "/home/marcelo/Development/fork/fastapi/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/starlette/responses.py", line 167, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 61, in sender
    await send(message)
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/anyio/streams/memory.py", line 215, in send
    await send_event.wait()
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 1843, in wait
    await checkpoint()
  File "/home/marcelo/.pyenv/versions/fastapi3.7/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 515, in checkpoint
    await sleep(0)
  File "/home/marcelo/.pyenv/versions/3.7-dev/lib/python3.7/asyncio/tasks.py", line 585, in sleep
    await __sleep0()
  File "/home/marcelo/.pyenv/versions/3.7-dev/lib/python3.7/asyncio/tasks.py", line 579, in __sleep0
    yield
concurrent.futures._base.CancelledError
```

**Pull request merged**
