### PR TITLE
[WIP] MultiDict and ImmutableMixin

### PR DESCRIPTION
**Pull request by taoufik07**
it's a **WIP**, I need to add some methods, tests and implement ImmutableMixin.

@tomchristie I need to know what do you think before moving further.

### CODE REVIEW

**Comment by taoufik07** [comment]
I've got another [implementation](https://gist.github.com/taoufik07/30ce9b76b8f6d291bafcffb8cf079baf) where I've used a `_dict` attribute instead of subclassing `dict`

**Comment by lovelydinosaur** [comment]
See #343.

A mutable `MultiDict` class, should subclass the existing `ImmutableMultiDict`, and add the extra MutableMapping API behavior for `__setitem__`, `__delitem__`, `pop`, `popitem`, `clear`, `update`, and `setdefault`.

Additionally, for multi-value updates we probably want `setlist(key, values)`, `appendlist(self, key, value)` and `setlistdefault(self, key, default_list=None)`.

**Comment by taoufik07** [comment]
in #343 removing an item gonna be expensive, cause we need to remove every occurrence in `_list`

**Comment by taoufik07** [comment]
Finally got some time, check this https://github.com/taoufik07/starlette/tree/MultiDict-2

**Comment by lovelydinosaur** [comment]
> in #343 removing an item gonna be expensive, cause we need to remove every occurrence in _list

I'm not concerned about that. It's a rare operation, typically small list sizes, and only an `O(n)` operation.

**Comment by lovelydinosaur** [comment]
Closing this off now, given #343.

Still up for a `MultiDict` implementation that builds on top of the existing `ImmutableMultiDict` class.

**Comment by taoufik07** [comment]
> I'm not concerned about that. It's a rare operation, typically small list sizes, and only an `O(n)` operation.

Okay !

**Comment by taoufik07** [comment]
@tomchristie I did it your way (I guess xD) https://github.com/taoufik07/starlette/tree/multidict-3

**Comment by lovelydinosaur** [comment]
Opened the PR here, with comments: https://github.com/encode/starlette/pull/345

**Pull request closed without merging**
