### PR TITLE
mkdocs: Added dark theme for the documentation

### PR DESCRIPTION
**Pull request by gbdlin**
mkdocs: expanded theme configuration to add alternative dark theme. The default theme will be determined by the users system theme by the `prefers-color-scheme` media query.

The primary color for the dark theme was changed to `blue`, instead of the default `indigo` to improve readability of links.

### CODE REVIEW

**Comment by graingert** [comment]
@gbdlin can you include a screenshot?

**Comment by gbdlin** [comment]
Here's the screenshot:
image

and working demo site: https://starlette-docs.gbd.one/

The default color scheme when user enters the website is determined by `prefers-color-scheme` media query reported by his browser, which is dependent on the browser settings, browser theme or OS theme (depending on the browser) and can be simulated by using developer tools. User can still change the theme by clicking the bulb icon next to the search bar.

**Review by kozzza — APPROVED** [review]

**Comment by Kludex** [comment]
@gbdlin Awesome idea! :tada:

Would you mind solving the conflicts?

**Comment by gbdlin** [comment]
@Kludex done!

**Review by Kludex — APPROVED** [review]
LGTM! Thanks, @gbdlin ! :tada:

I'll wait to see if some any member has an opinion on the colors before merging it.

**Pull request merged**
