### PR TITLE
Make StaticFiles methods internal

### PR DESCRIPTION
**Pull request by aminalaee**
As far as I could see all `StaticFiles` methods should be internal, and shouldn't be used from outside.

This PR will change all existing methods to internal to reflect that.

### CODE REVIEW

**Comment by florimondmanca** [comment]
Dunno, it's fiddly. What if some people do rely on these methods today? The fact that our tests rely on these methods is interesting. Could we rearrange things to _not_ call these methods at all, meaning that low-level users _would_ have a way to not use these methods for common low-level use cases?

**Comment by aminalaee** [comment]
@florimondmanca I think most of them are already private-ish requiring the request scope from `__call__`.
As for our own tests, it's already described why we can't use the test client in that test.

I can't think of any re-arrangements, I thought about modifiying `get_directories` as is so It's kept public, but I don't think it would be much useful as we can already access `staticfiles.all_directories`. Do you have anything in mind?

P.S. We can also mark them for deprecation so we can change it later.

**Comment by lovelydinosaur** [comment]
I think I'd probably second @florimondmanca here. The pragmatic path here is probably just to leave things as they are.

**Comment by aminalaee** [comment]
Cool, then I close this.

**Pull request closed without merging**
