### PR TITLE
Add a encoder argument for the function __init__ of class - JsonRespo…

### PR DESCRIPTION
**Pull request by lishukan**
…nse (#1250)

This argument have default value :None. And this argument is  related to argument 'cls' of function - json.dumps(...cls=)

### CODE REVIEW

**Comment by lishukan** [comment]
When I use the class -- to serialize(jsonify) a response, I find that I can not assign the special JsonEncoder . Sometime i have to rewrite the JsonResponse class 。

**Comment by lishukan** [comment]
sometime, we  have to rewrite JsonResponse class .for example , when you want to  use json to serialize  some special object ,like   datetime.datetime or Decimal  ....

**Comment by lishukan** [comment]
so I write  provide this pull request   for  serializing those special object .  you can  code your  encoder  class ,and add it to 
 args of   JsonResponse.__init__ .

**Comment by Kludex** [comment]
Explanation on why it's closed on https://github.com/encode/starlette/issues/1250#issuecomment-993882247

@lishukan Thanks for the PR.

**Pull request closed without merging**
