### PR TITLE
Documenting how `StreamingResponse` adheres to ASGI spec

### PR DESCRIPTION
**Pull request by jamesbraza**
# Summary

I was reading the source code how `StreamingResponse` works, and found myself in-depth researching `more_body`.

This PR just upstreams that knowledge (and links the ASGI spec) in the docs.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
I don't find this clear. 🤔

**Comment by jamesbraza** [comment]
What aspect do you find unclear? Also, feel free to make commits to this PR directly

My motivation here is helping others get a better head-start on understanding `StreamingResponse`'s inner workings

**Review by hasansezertasan — CHANGES_REQUESTED** [review]
This is unclear because there is no mention of "more_body" in the file @jessebraham edited.

I saw your [PR](https://github.com/tiangolo/fastapi/pull/10932) on FastAPI repo. It's good for you, to search in depth... But I think we need to KISS the docs. I see what you are trying to do but developers use all kinda technologies and we need to leave some space for devs to search/discover. No documentation can have all answers (or refs) and IMO it's a good thing.

In the end, there is no mention of "more_body" in the docs. It's just confusing me and there is already a reference for ASGI Specs in the `index.md` file.

**Comment by jamesbraza** [comment]
I have just tweaked the wording and moved it to an `info` section for visual separation.  @Kludex let me know if there are parts still confusing you

**Comment by Kludex** [comment]
I'm not convinced. We can wait for other member to comment.

**Comment by jamesbraza** [comment]
Sounds good. To follow up on a few comments:

> I think we need to KISS the docs.

Yep sounds good. My last commit tries to further simplify and be less technical, while still containing relevant information.

> In the end, there is no mention of "more_body" in the docs.

There's no other mentions of `more_body` because it's specific to streaming, and this is the streaming docs. So I am not sure if it would be documented elsewhere.

> It's just confusing me and there is already a reference for ASGI Specs in the `index.md` file.

As far as there being other links to the ASGI spec in the docs, I think it's fine to link it several times, I don't think many people ever read full documentation, just relevant portions

Thanks again all

**Comment by tiangolo** [comment]
Thanks!

But I don't really think it's a good idea to link to the ASGI spec in the docs and point newcomers learning about the framework to the dry and long specification, it's much more complicated and not really necessary for most people.

As Starlette already mentions in several places it is an ASGI framework, I would think people who wanted to know more about the details of each specific part would be able to go and read the spec, and it also applies to many other parts, not just `StreamingResponse`... So I would be more inclined to not take this one. 😅

**Comment by tiangolo** [comment]
Sorry, closed instead of commenting. 😅

**Comment by jamesbraza** [comment]
My motivation here is I use `StreamingResponse` in a somewhat performant `FastAPI` system to stream JSON data, and had to create a subclass for this. So I wanted to know what mechanism it used, if the connection was long-lived, etc.

Understanding the inner workings for me was somewhat nontrivial, involving lots of IDE debugging (probably because I am new to ASGI). So I tried to leave behind a paper trail to help "the next guy" in figuring out how the streaming actually works, without resorting to the debugger.

I think the thing with PRs like this is, once you know it, you forget what it's like not to know.

Anyways, I can let others make the call here, thanks for participation!

**Comment by Kludex** [comment]
I agree with @tiangolo .

Thanks for the PR, but I don't think this should be included.

**Pull request closed without merging**
