### PR TITLE
Add reason support for websocket.close

### LINKED ISSUE #991: [Feature] Reason for websocket.close
I've recently started actively developing with websockets in starlette. When closing a websocket you can provide a code e.g. 1000, 1008 … to tell the client the basic reason. But the websocket protocol allows the developer to also give UTF-8-encoded data as a complementary description/ reason. This would be useful in multiple cases such as mentioning the specific violitioan for code 1008 (POLICY VIOLIATION). [Websockets](https://websockets.readthedocs.io/en/stable/api.html?highlight=reason#websockets.protocol.WebSocketCommonProtocol.close) supports this too and their [implementation](https://websockets.readthedocs.io/en/stable/_modules/websockets/protocol.html#WebSocketCommonProtocol.close) could maybe help.

Specification: [https://tools.ietf.org/](https://tools.ietf.org/html/rfc6455#section-5.5.1)

### PR DESCRIPTION
**Pull request by Chaostheorie**
Resolve #991.

### CODE REVIEW

**Comment by Chaostheorie** [comment]
I'm sorry for the mess. Couldn't get the tests working on my machine

**Comment by lovelydinosaur** [comment]
We'll take a pass on this. "code" is part of the ASGI spec, but "reason" isn't.

**Comment by Kludex** [comment]
@Chaostheorie I can't reopen this PR as the fork was deleted, jfyk.

**Comment by Chaostheorie** [comment]
@Kludex I will redo it since it was based on a year-old codebase anyway. Give me a second …

Edit: Had smth come up, anyways #1339 has the old changes recreated and stashed. This might also need some tests to support the new reason option

**Pull request closed without merging**
