### PR TITLE
Add explicit UJSONResponse

### PR DESCRIPTION
**Pull request by lovelydinosaur**
Needs docs updating.
Would need README.md and index.md notes on micro-performance nonsense.

### CODE REVIEW

**Comment by Midnighter** [comment]
I was wondering about this one, what about a general response class that you can instantiate with just the `dumps` equivalent of your package of choice (or a partial with the preferred arguments set). Or set `dumps` as a class variable.

**Comment by lovelydinosaur** [comment]
@Midnighter I'd kinda considered that yup, tho it gets a bit more icky in that we'd quite like different arguments in the UJSON case. Happy to consider alternatives, but it's not obvious to me that there's better answers than simply subclassing JSONResponse with whatever `render` method you want.

**Comment by Midnighter** [comment]
That's why a partial might be a good solution.

**Comment by lovelydinosaur** [comment]
Let me put it this way around instead: I’m not convinced that `return JSONResponse(..., dumps=ujson.dumps)` is better than `return UJSONResponse(...)`

(Or equivalently for alternative subclasses)

**Comment by Midnighter** [comment]
Fair enough :smiley: what about:

```python
from starlette import JSONResponse

JSONResponse.dumps = partial(...)
```
Although, as you say the classes are very thin anyway and it's actually very explicit then what you return. My only suggestion is then to move `UJSONResponse` (and each sibling like it) into its own module that is not automatically imported. A developer would then get it `from starlette.ujson_response import UJSONResponse`, for example, and if `ujson` is not available the resulting `ImportError` is for the developer to handle.

**Comment by alexbotello** [comment]
I don’t think it’s use case warrants it’s own module. In fact, I don’t really think it’s neccessary to have more than two subclasses.

**Comment by lovelydinosaur** [comment]
Published as 0.4.0 (Version bump because JSONResponse is stricter than UJSONResponse for some edge-cases)

**Pull request merged**
