### PR TITLE
warn instead of raise for missing env file

### PR DESCRIPTION
**Pull request by mathause**
# Summary

Adresses #2422

Let me know if you want a custom Warning and/ or any doc changes.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
Thanks.

**Comment by mathause** [comment]
Thanks & sorry for the churn.

**Comment by tvasenin** [comment]
@Kludex Could you pls release the fixed version asap? (maybe even backport to 0.36.x releases, since it's used by latest FastsAPI v0.109.2)

**Comment by Kludex** [comment]
@tvasenin Can you open a PR analogous to this: https://github.com/encode/starlette/pull/2457 with 0.37.1?

**Pull request merged**
