### PR TITLE
Version 0.18.0

### PR DESCRIPTION
**Pull request by Kludex**
### Checklist
- [x] https://github.com/encode/starlette/pull/1361
- [x] #1422 
- [x] #1360 #1423 
- [x] ~https://github.com/encode/starlette/pull/1270~ https://github.com/encode/starlette/pull/1397
- [x] #1410 
- [x] https://github.com/encode/starlette/pull/1401
- [x] #1417 
- [x] #1387 

I've added many items above because they are supposedly very short i.e. it's just to make a decision on them.

If any other member wants to add any item on the checklist, feel free to do so.

EDIT: **I've removed the checklist items, because it's taking too long to release.**

### CODE REVIEW

**Comment by aminalaee** [comment]
It would be great if we could include these too:
https://github.com/encode/starlette/pull/1385
<del>https://github.com/encode/starlette/pull/1400</del>

**Comment by Kludex** [comment]
I've removed some of my requisites for this release to speed up things.

**Comment by Kludex** [comment]
Draft created: https://github.com/encode/starlette/releases
Changes for this release: https://github.com/encode/starlette/compare/0.17.1...master

**Comment by aminalaee** [comment]
I've updated the Checklist, looks good, maybe we can update the changelog and release it.

**Review by aminalaee — APPROVED** [review]
Awesome. Just a reminder to update the release date 🎉

**Comment by adriangb** [comment]
Great job and thank you all!

**Pull request merged**
