### PR TITLE
Deduplicate failure text in CORS preflight response

### PR DESCRIPTION
**Pull request by laggardkernel**
Break the loop to t avoid appending string `headers` into `failures` multiple times. Otherwise it causes duplication in CORS response text (not response header).

```diff
        elif requested_headers is not None:
            for header in [h.lower() for h in requested_headers.split(",")]:
                if header.strip() not in self.allow_headers:
                    failures.append("headers")
+                    break
        ...
        if failures:
            failure_text = "Disallowed CORS " + ", ".join(failures)
            return PlainTextResponse(failure_text, status_code=400, headers=headers)
```

### CODE REVIEW

**Comment by JayH5** [comment]
Thanks. Any way we can add a test for this?

**Comment by laggardkernel** [comment]
It's such a trivial change, just break the loop to avoid appending a value into the same list multiple times. Do we really need a test for it? @JayH5

**Comment by laggardkernel** [comment]
Anyway, I added a test and force pushed the commit.

**Review by JayH5 — APPROVED** [review]
> It's such a trivial change, just break the loop to avoid appending a value into the same list multiple times. Do we really need a test for it?

I didn't completely understand this at first so just thought bug == test please 🙂. Probably wasn't super necessary but can't hurt, thanks.

**Pull request merged**
