### PR TITLE
Disable graphiql by default

### PR DESCRIPTION
**Pull request by jordaneremieff**
This allows for GraphIQL to be enabled/disabled (default: disabled) using an additional keyword argument. It is a good security practice to disable this console on production systems.

### CODE REVIEW

**Comment by tiangolo** [comment]
My 2 opinionated cents:

I like the idea of being able to turn it off, but I'm not sure about having it off by default.

For example, GitHub has it on, with production data: https://developer.github.com/v4/explorer/

**Comment by jordaneremieff** [comment]
I think having it default to off is more appropriate because it is considered a development tool first as well as it being [recommended](https://graphql.org/learn/serving-over-http/#graphiql) to disable it in production.  This would also be consistent with the various other Graphene integrations for popular frameworks.

**Review by lovelydinosaur — CHANGES_REQUESTED** [review]
Thanks @erm! I'm happy enough with us defaulting to having it on, but the configuration switch would make sense.

**Comment by lovelydinosaur** [comment]
👍

**Pull request merged**
