### PR TITLE
Add Third Parties section to docs with: Starlette APISpec, Starlette API, Responder and FastAPI

### PR DESCRIPTION
**Pull request by tiangolo**
This PR adds a section to the docs at the end with third-party packages.

I'm still not sure if "Third Parties" is the best name. Other options that come to mind:

* External Packages
* Plugins (even though 2 of those are actually frameworks, powered by Starlette)
* Third Party Packages (long, but more explicit)

Also, I don't know if I'm being too verbose in the docs.

---

@Woile and @PeRDy, do you have anything to comment there about Starlette APISpec and Starlette API? (I imagine @kennethreitz probably won't care too much about Responder's section).

### CODE REVIEW

**Comment by perdy** [comment]
Thanks for your effort adding other libs. I don't have anything to comment, happy with it.

**Comment by lovelydinosaur** [comment]
Nice work! 😄

**Comment by tiangolo** [comment]
Awesome! Thanks!

**Comment by woile** [comment]
Good job! Looks good.

Should we also add some sections about ORMs and about data serialization (like marshmallow & pydantic)?

**Comment by lovelydinosaur** [comment]
I guess *at the moment* I'd probably consider that as out-of-scope, but I could probably go either way on it.

**Pull request merged**
