### PR TITLE
Adding timeout to WebSocket session receive on test client

### PR DESCRIPTION
**Pull request by serans1**
# Summary

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by serans1** [comment]
Hi, 
Can you share why this was closed ? 
Testing WebSocket currently hangs if there is no response

**Comment by serans1** [comment]
Hi,
Can you share why this was closed ?
Testing WebSocket currently hangs if there is no response

**Comment by Kludex** [comment]
You didn't provide any description or look for previous PRs and issues about the subject.

**Comment by serans1** [comment]
I get your point, I see it here
https://github.com/encode/starlette/discussions/2195
for reference, this PR is right and timeout should be added without pytest
extensions.
No intention in getting into holy wars, just yet another take on the
matter.

**Pull request closed without merging**
