### PR TITLE
Ensure query params behavior matches standard mappings.

### LINKED ISSUE #333: QueryParams unexpected bahavior
Hey, in QueryParams when calling the `.keys()` it returns the keys from the `self._list` which can return duplicate keys if a key have multiple values. Same for `.values()` and `.items()`, it returns all the values, while the expected behavior is to return for each key the last value.

```python
>>> q = QueryParams(query_string="a=1&a=2")
>>> q.keys() # ['a', 'a'] the expected ['a']
>>> q.values() # [1, 2] the expected [2]
>>> q.items() # (a, 1) (a, 2) the expected (a, 2)
```
I can easily fix those, but I suggest to create a MultiValueDict that can be subclassed by other classes. 

So what do you think, should I keep it that way and fix the behavior or add a MultiDict ?

** In the QueryParams implementation, the items are stored in both a dict and a list, is it more efficient than django's `Mapping[str, List]` or just because back then there were more important things to do.

### PR DESCRIPTION
**Pull request by lovelydinosaur**
Closes #333
Superseeds #337

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Question: Do we consider this to be a straight-up bugfix, or an API behavior change?

**Comment by taoufik07** [comment]
A bugfix, cause that's the behavior that would anyone expect

**Comment by lovelydinosaur** [comment]
Right then. Possible follow ups:

1. I'd be perfectly happy to see `keys`, `values` and `items` return "keyview"/"valuesview"/"itemsview" or whatever the heck those are called. It'd need some work on the type annotations to get right.
2. Base class - I don't particularly care. I'd be happy to see a pull request for it, and judge it on merit, but keep in mind that the general cases would not be str: str as we have now, and might need to include both mutable and immutable types?

**Comment by taoufik07** [comment]
**Update**: Tweaking the QueryParams is not a good idea, because removing an item gonna be expensive since we need to remove it from `_dict` and remove each occurrence in `_list`.
So I think we should go with Mapping[Any, List[Any]].

**Comment by lovelydinosaur** [comment]
Okay, we now have `FormData`. Both `FormData` and `QueryParams` could inherit from a shared `ImmutableMultiDict` base class if we wanted. That'd be the first step.

We'd then want to also add a (mutable) `MultiDict`, but we should address that as a separate issue.

**Comment by lovelydinosaur** [comment]
`FormData` and `QueryParams` themselves should remain immutable. If a user wants a mutable data structure containing that info, then make a mutable copy eg. `query_params = MultiDict(request.query_params)`

**Comment by taoufik07** [comment]
Alright !

**Pull request merged**
