### PR TITLE
Fix publish Github Action

### PR DESCRIPTION
**Pull request by aminalaee**
# Summary

Failed the pipeline for publish: https://github.com/encode/starlette/actions/runs/5541452034/jobs/10114867807

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
Oh god... 😭 

Thanks @aminalaee

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
I guess I need to delete the tag, and the GitHub release?

**Comment by Kludex** [comment]
I can't delete a tag...

**Comment by aminalaee** [comment]
No I think you can just re-run the publish Github action.

**Comment by aminalaee** [comment]
You can delete tag and publish again, but I think the action re-start should solve it.

**Comment by Kludex** [comment]
Just tried, it doesn't.

**Comment by aminalaee** [comment]
Ugh, it's pulling the the previous commit, so it's not working.
I think you need to re-create the tag then :cry:

**Pull request merged**
