### PR TITLE
Background Thread created by WebSocketTestSession should exit when close() is called

### LINKED ISSUE #947: Background Thread created by WebSocketTestSession should exit when close() is called
Hello!

I've been trying to write tests for a starlette websocket API. 

Only one problem - the server isn't written in a way to exit nicely when a websocket is closed. 
As a result, the tests just sit there, because `websocket_connect()` won't exit until the server does.

By looking at the source, I figured that `WebSocketTestSession` is waiting for the session thread (`_run()`) to complete.

Can we please make it so that it stops the server when `close()` is called?

---

I've cobbled together a small [commit](https://github.com/devxpy/starlette/commit/41907e863220b8b34f6bcc0d8f3a8d1241ded8eb) to make this work. If you're on board with this change, I'd love to upstream this.

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/947">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/947/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by devxpy**
Fixes https://github.com/encode/starlette/issues/947

### CODE REVIEW

**Comment by graingert** [comment]
I think asgiref.sync.sync_to_async(threadsensitive=True) might help here

**Comment by Kludex** [comment]
Closing this as stale.

Let's trial ~#948~ #947 first, then come back to a solution later on - if applicable.

**Comment by nathanielobrown** [comment]
> Let's trial https://github.com/encode/starlette/pull/948 first, then come back to a solution later on - if applicable.

@Kludex, this is #948! Maybe you linked the wrong issue? I'm looking for a fix to this and if there is another issue/PR open it would be useful to know

**Comment by Kludex** [comment]
Updated the message 😅

**Pull request closed without merging**
