### PR TITLE
CORS-middleware-use-explicit-origin-with-credentials

### PR DESCRIPTION
**Pull request by Swati-Sneha**
The starting point for contributions should usually be [1832](https://github.com/encode/starlette/issues/1832)

Simple documentation typos may be raised as stand-alone pull requests, but otherwise please ensure you've discussed your proposal prior to issuing a pull request.

This will help us direct work appropriately, and ensure that any suggested changes have been okayed by the maintainers.

- [ ] Initially raised as discussion #...

### CODE REVIEW

**Comment by adriangb** [comment]
Can you clarify what this is and link to an issue? Otherwise we’ll have to close this PR

**Comment by Swati-Sneha** [comment]
Hi Adrian,

I am new to open source and this is my first issue. I was trying to solve
the issue discussed here: https://github.com/encode/starlette/issues/1832

I spoke to Marcelo regarding this, and I have understood I need to
investigate more on this

**Comment by Kludex** [comment]
Please change the title to something more suitable, add a better description, and as I said before: I need to reread the issue, and we need to know what's the behavior of the others web frameworks (flask, django, and maybe others because I believe those two differ in this particular point).

**Comment by Kludex** [comment]
@Swati-Sneha Are you still interested in this? :eyes:

**Comment by Kludex** [comment]
@Swati-Sneha I'll be closing this for the time being, feel free to reopen based on our comments. 👍

**Pull request closed without merging**
