### PR TITLE
Allow "name" argument on `url_for()` and `url_path_for()`

### LINKED ISSUE #608: "url_for" signature prevents use of "name" in path arguments
I'm implementing an API in Fastapi, using `APIRouter`s for different resources.
When I want to get the URL of an item in a resource, I use the `starlette.requests.Request` objects `url_for()` method.
When I have a function with a path `/resource/{name}` I cannot use `url_for()` to get the URL, because it will result in:
```
TypeError: url_for() got multiple values for argument 'name'
```
Reproduce with:
```
def func(name, **path_params):
    pass
func("foo", name="bar")
```

As a workaround I have renamed the path variable in my API, but `name` was really fitting, and what I wanted to use, and not at all an uncommon variable name.
From what I see, `name` in `url_for()` seems to be the name of the referenced method in `APIRouter`. Changing the signature of `url_for()` to use `router_method` instead of `name`, would make a collision with the key word arguments in `path_params` less likely. Result would be:
```
def url_path_for(self, router_method: str, **path_params: str) -> URLPath:
```
An inspection on the used arguments could be used to log a deprecation warning until the next release, when `url_path_for()` is used with a named `name=...` instead of positional.

If this proposal is acceptable, I'd create a PR.

### PR DESCRIPTION
**Pull request by Kludex**
- Closes https://github.com/encode/starlette/issues/608
- Replaces https://github.com/encode/starlette/pull/611

### CODE REVIEW

**Comment by Kludex** [comment]
@encode/maintainers :eyes: :pray:

**Comment by adriangb** [comment]
This looks good to me. But admittedly I don't really use this functionality so I'd like someone who actually uses this to be the one approving ✅

**Comment by Kludex** [comment]
I want to make a premature release with the lifespan state that was included, but since I included https://github.com/encode/starlette/pull/1385, it may be good to also include this in the release. :sweat_smile: 

@alex-oleshkevich @abersheeran would you mind checking this? :pray:

**Review by abersheeran — APPROVED** [review]
I feel very good. 😊

**Pull request merged**
